baseURL = 'https://letterstamp.com/'
languageCode = 'en-us'
title = "letterstamp"
theme = 'hugo-book'

[params]
    BookTheme = 'light'
    BookSection = 'info'
    BookSearch = false

[markup.goldmark.renderer]
  unsafe = true