baseURL = 'https://singleplot.com/'
languageCode = 'en-us'
title = "single plot"
theme = 'hugo-book'

[params]
    BookTheme = 'light'
    BookSection = 'info'
    BookSearch = false
    BookLogo = 'favicon.png'

[markup.goldmark.renderer]
  unsafe = true